#Guion para analizar la variacion temporal en la prevalencia de galls
#Data generated by P Murua-Andrade, University of Aberdeen
#Modifications: FPL (20180910)
#----------------------------------------------------------------
# 0. Configuracion
#----------------------------------------------------------------
# 0.1. Limpio espacio de trabajo
rm(list=ls())
# 0.2. Modifico directorio 
# setwd("~/Dropbox/Radboud University/publicaciones/Pedro/datos/")#Defino directorio de trabajo
getwd()     #verifico directorio de trabajo
# 0.3. Creo variable conteniendo fecha de hoy (descubriran la utilidad de esto mas adelante)
today<-format(Sys.Date(),"%Y%m%d")
# 0.4. librerias
library(car)
library(MASS)
library(lme4)
library(geiger)
library(MuMIn)
library(AICcmodavg)#AIC corregido por numero de parametros
library(lsmeans)#comparaciones multiples
library(multcompView)#para mostrar simbolos de differencias
#----------------------------------------------------------------
#0.5. Leo datos de gall
datos<-read.csv("chascon.v3.csv",header=T)
str(datos)
datos$Nquad<-as.factor(datos$Nquad)
summary(datos)

#0.6. Funciones
#----------------------------------------------------------------
vif.mer<-function(fit){   ## adapted from rms:vif
  v<-vcov(fit)
  nam<-names(fixef(fit)) ## exclude intercepts
  ns<-sum(1*(nam=="Intercept"|nam=="Intercept"))
  if(ns>0){
    v<-v[-(1:ns),-(1:ns),drop=FALSE]
    nam<-nam[-(1:ns)]
  }
  d<-diag(v)^(0.5)
  v<-diag(solve(v/(d%o%d)))
  names(v)<-nam
  v
}

##################################################################################################################################
# Primero nos enfocaremos en la variable Fitness. Para ello, utilizaremos GLMMs para
# evaluar si esta variable binaria (Shapely/Malformed) esta en funcion de las 
# distintas variables explicativas que se tienen (stage,Tlength, month,etc). 
# Es inherente el uso de este tipo de aproximacion dado el tipo de 
# variable de respuesta. Secundariamente, se necesita considerar la falta de
# independencia atribuida al muestreo de la misma cuadrata traves del tiempo (1|Nquad) 
# para cada set de modelos. Las distintas versiones de GLMM fueron implementadas 
# en la libreria lme4 (Bates et al 2015) using la funcion {glmer}. Para cada caso,
# se usó una distribucion binomial con funcion de vinculo de tipo logit. Los datos 
# ambientales no fueron incluidos dentro de los modelos dado que la variabilidad entre meses fue baja. 
###################################################################################################################################
# Question: What are the drivers trigger changes of the gall-prevalence in Lessonia?.
# Para ello planteo una serie de GLMMs

# Modelo full
gall.full<-glmer(Fitness2~Month+Maturity+T.length+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.full)

vif.mer(gall.full)#descartamos T.length del modelo dado VIF es mayor a 5

gall.fit1<-glmer(Fitness2~Month+Maturity+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.fit1)

vif.mer(gall.fit1)
drop1(gall.fit1,test = "Chisq")#simplificamos el modelo excluyendo la densidad

gall.fit2<-glmer(Fitness2~Month+Maturity+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.fit2)
Anova(gall.fit2)

#             Chisq Df Pr(>Chisq)    
# Month     201.142 11  < 2.2e-16 ***
# Maturity   27.608  1  1.486e-07 ***
# Age.stage 141.416  2  < 2.2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Ahora testeamos Full con estacion en ves de meses
gall.fulla<-glmer(Fitness2~season+Maturity+T.length+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.full)

vif.mer(gall.fulla)#Excluimos T.length

gall.fullb<-glmer(Fitness2~season+Maturity+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
vif.mer(gall.fullb)
drop1(gall.fullb,test = "Chisq")

gall.fullc<-glmer(Fitness2~season+Maturity+Age.stage+(1|Nquad),family = binomial,data=datos)
vif.mer(gall.fullc)
drop1(gall.fullc,test = "Chisq")


#Ok, ahora comparo modelo que considera  season y el otro que considera month como variables explicativas

model.list.full<-list(gall.fit2,gall.fullc)
model.names.full<-c("Full con Month","Full con season")
model.sel.full<-aictab(model.list.full, model.names.full, second.ord=T,sort = FALSE)
model.sel.full#el mas informativo es el que considera el mes como variable explicativa

#                   K   AICc   Delta_AICc   AICcWt      LL
# Full con Month   16  864.60       0.00      1 -416.08
# Full con season   8  977.65     113.05      0 -480.77

#Chequeo por overdispersion
rdev <- sum(residuals(gall.fit2)^2)
mdf <- length(fixef(gall.fit2))
rdf <- nrow(datos)-mdf
overd<-rdev/rdf
overd#0.6555025 es menor a 1 lo que quiere decir que no hay overdisperion


####################################################################
# Ahora podriamos hacer las predicciones basado en el modelo gall.fit2
# para calcular las probabilidades (individuales) de observar una planta enferma
# para cada mes, cuadrata (efecto aleatorio), etapa de vida y madurez
####################################################################
pred.mat=expand.grid(Month=unique(datos$Month),Age.stage=unique(datos$Age.stage),
                     Maturity=unique(datos$Maturity),Nquad=unique(datos$Nquad))
pred.mat$prob=predict(gall.fit2,newdata=pred.mat,level=0, type="response")

# Test a posteriori 
compara<-lsmeans(gall.fit2, pairwise~Month, adjust="tukey")
summary(compara)
cld(compara)

#Ahora deberias plotear a tu pinta, podrias por ejemplo mostrar el efecto de los meses
# en adultos y ejemplares fertiles usando las predicciones calculadas en las lineas
# 141-143.

# ver ejemplos (sjPlot)
# https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_model_estimates.html

plot(prob~Month,data = subset(pred.mat,pred.mat$Maturity=="Fertile"&pred.mat$Age.stage=="Adult"))
