# ------------------------------------------------------------------------------
# Script to analyse the temporal variation in the prevalence of galls 
# 
# Data generated by Pedro Murua-Andrade, University of Aberdeen 
# 
# Script created by Félix P Leiva on 20180910 (felixpleiva@gmail.com) 
# Modified by Félix P Leiva on 20221013 (felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# ------------------------------------------------------------------------------
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(car)
library(MASS)
library(lme4)
library(geiger)
library(MuMIn)
library(AICcmodavg)
library(multcomp)
library(multcompView)
library(ggplot2)
library(corrplot)
library(gridExtra)
#-------------------------------------------------------------------------------
# Load data
datos<-read.csv("../Data/chascon.v3.csv",header=T)
#-------------------------------------------------------------------------------
#Load Function to calculate VIF
source("../Functions/Variance Inflation Factor.R")
#-------------------------------------------------------------------------------
#Explore data
str(datos)
datos$Nquad<-as.factor(datos$Nquad)
summary(datos)
# Number of zeros and Ones
table(datos$Fitness2)
#  0   1 
# 655 599
#-------------------------------------------------------------------------------
# Question: What are the drivers trigger changes of the gall-prevalence in Lessonia?.

# Full model
gall.full<-glmer(Fitness2~Month+Maturity+T.length+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.full)

vif.mer(gall.full) # excude Total length bc vif > 5

# simplify the model
gall.fit1<-glmer(Fitness2~Month+Maturity+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.fit1)

vif.mer(gall.fit1)
drop1(gall.fit1,test = "Chisq") # Density is not significant

# simplify the model
gall.fit2<-glmer(Fitness2~Month+Maturity+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.fit2)
Anova(gall.fit2)

# Response: Fitness2
#             Chisq Df Pr(>Chisq)    
# Month     201.137 11  < 2.2e-16 ***
# Maturity   27.607  1  1.486e-07 ***
# Age.stage 141.421  2  < 2.2e-16 ***
 

#Lets fits the model with season as predictor instead of months
gall.fulla<-glmer(Fitness2~season+Maturity+T.length+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.full)

vif.mer(gall.fulla) # Exclude T.length

#refit the model
gall.fullb<-glmer(Fitness2~season+Maturity+Density+Age.stage+(1|Nquad),family = binomial,data=datos)
vif.mer(gall.fullb)

drop1(gall.fullb,test = "Chisq")

#refit the model after remove density
gall.fullc<-glmer(Fitness2~season+Maturity+Age.stage+(1|Nquad),family = binomial,data=datos)
vif.mer(gall.fullc)
drop1(gall.fullc,test = "Chisq")

# Lets now compare model with month and season as predictor 
model.list.full<-list(gall.fit2,gall.fullc)
model.names.full<-c("Full with Month","Full with season")
model.sel.full<-aictab(model.list.full, model.names.full, second.ord=T,sort = FALSE)
model.sel.full

# Model selection based on AICc:
#   
#                   K   AICc Delta_AICc AICcWt      LL
# Full with Month  16 864.60       0.00      1 -416.08
# Full with season  8 977.65     113.05      0 -480.77


#check overdispersion
rdev <- sum(residuals(gall.fit2)^2)
mdf <- length(fixef(gall.fit2))
rdf <- nrow(datos)-mdf
overd<-rdev/rdf
overd#0.6555025 is below 1, so is ok

summary(gall.fit2)
r.squaredGLMM(gall.fit2)
####################################################################
# Lets make predictions
pred.mat=expand.grid(Month=unique(datos$Month),Age.stage=unique(datos$Age.stage),
                     Maturity=unique(datos$Maturity),Nquad=unique(datos$Nquad))
pred.mat$prob=predict(gall.fit2,newdata=pred.mat,re.form= ~(1|Nquad), type="response")

# A posteriori test months
compara.meses<-lsmeans(gall.fit2, pairwise~Month, adjust="tukey")
summary(compara.meses)
cld(compara.meses)

# A posteriori test stage
compara.etapa<-lsmeans(gall.fit2, pairwise~Age.stage, adjust="tukey")
summary(compara.etapa)
cld(compara.etapa)

# A posteriori test Maturity
compara.madurez<-lsmeans(gall.fit2, pairwise~Maturity, adjust="tukey")
summary(compara.madurez)
cld(compara.madurez)

#Figure 1
b1 = ggplot(pred.mat, aes(x=Month, y=prob)) +
  geom_boxplot(outlier.colour=NA, fill=NA, colour="grey20")+
  xlab("Months") + ylab("Predicted probabilities")
b1

png("../Outputs/1.1. Gall prevalence per month.png", height=7, width=9, units="in", res=200)
grid.arrange(b1,nrow=1)
dev.off()

#Figure 2
b2 = ggplot(pred.mat, aes(x=Maturity, y=prob)) +
  geom_boxplot(outlier.colour=NA, fill=NA, colour="grey20")+
  xlab("") + ylab("Predicted probabilities")
b2

png("../Outputs/1.2. Gall prevalence per maturity.png", height=7, width=9, units="in", res=200)
grid.arrange(b2,nrow=1)
dev.off()


#Figure 3
b3 = ggplot(pred.mat, aes(x=Age.stage, y=prob)) +
  geom_boxplot(outlier.colour=NA, fill=NA, colour="grey20")+
  xlab("Life-stage") + ylab("Predicted probabilities")
b3

png("../Outputs/1.3. Gall prevalence per stage.png", height=7, width=9, units="in", res=200)
grid.arrange(b3,nrow=1)
dev.off()

#########################################################################################
gall.age<-glmer(Fitness2~Age.stage+(1|Nquad),family = binomial,data=datos)
summary(gall.age)

gall.month<-glmer(Fitness2~Month+(1|Nquad),family = binomial,data=datos)
summary(gall.month)

gall.maturity<-glmer(Fitness2~Maturity+(1|Nquad),family = binomial,data=datos)
summary(gall.maturity)

gall.length<-glmer(Fitness2~T.length+(1|Nquad),family = binomial,data=datos)
summary(gall.length)
#########################################################################################
model.list<-list(gall.age,gall.month,gall.maturity,gall.length)
model.names<-c("Life-stage","Month","Maturity","Length")
model.sel<-aictab(model.list, model.names, second.ord=T,sort = FALSE)
model.sel
#########################################################################################
summary(datos$T.length)
pred=expand.grid(T.length=unique(datos$T.length),Nquad=unique(datos$Nquad))
pred$prob=predict(gall.length,newdata=pred,re.form= ~(1|Nquad), type="response")
plot(prob~T.length,data = pred,las=1)
#-------------------------------------------------------------------------------
#saving session information with all packages versions for reproducibility
#purposes
sink("../Outputs/1.4. Gall_prevalence_Lessonia_R_session.txt")
sessionInfo()
sink()
################################################################################
############################ END OF SCRIPT #####################################
################################################################################